.PHONY: clean All

All:
	@echo "----------Building project:[ CryptLB1 - Debug ]----------"
	@cd "CryptLB1" && "$(MAKE)" -f  "CryptLB1.mk"
clean:
	@echo "----------Cleaning project:[ CryptLB1 - Debug ]----------"
	@cd "CryptLB1" && "$(MAKE)" -f  "CryptLB1.mk" clean
